### PR TITLE
dockerfile working on raspberry pi

### PR DESCRIPTION
**Pull request by vicentedealencar**
First of all thanks for this awesome project, it is so easy to deploy to now.

So I fiddle a little and got it running on a docker container on a raspberry pi with this:
`docker run -p 80:8004 --restart='always' --name react-universally-d react-universally`

Only catch is that it is based on `.envnow` because `.env` is ignored by git.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
mindblown

**Comment by ctrlplusb** [comment]
That is super cool dude!  You have it actually running and serving off a raspberry pi!?!?!  Frikken awesome!  Do you have an actual use case you are trying to satisfy with this, or is it a completely experimental affair?

In terms of the PR I think it's great to consider including a Dockerfile, as it's more of a chore that an opinion on application architecture.  That said I think we should consider a base docker image that has as wide of an audience as possible if that makes sense?

**Comment by vicentedealencar** [comment]
I was planning to deploy a little react app using `now`, and found this awesome project that is much better than the one I was writing from scratch. Also, these days I had been playing with docker on pi, so decided to give it a try. This setup made it really easy to hack it together, and the least I could do is share back. :)

I am on windows with no docker setup, so I can't look this further, but changing the first line to `FROM node` should work for most people. But I think it is a good idea to leave a reference to pi. Either as a comment on the second line like: `# to run on raspberry pi use FROM FROM hypriot/rpi-node` or as a separate `Dockerfile.pi` as does [docker repo](https://github.com/docker/docker).

**Comment by ctrlplusb** [comment]
Thanks for kind words dude.  Really appreciate the feedback.

It's super cool that you have this running on a pi.  I'll defo look to include this somehow into the project.  Time to refresh my docker skills. :)

**Comment by ctrlplusb** [comment]
I'm going to close this for now, but fully intend to create a Dockerfile.  I'll be adding your configuration somewhere in the mix (docs/etc).

**Pull request closed without merging**
