### PR TITLE
Merge master into feature/redux-opinionated

### PR DESCRIPTION
**Pull request by SleepWalker**
Hello guys,

I've merged feature/redux-opinionated with master and I think it should be updated on github too, to simplify the life for other devs

### CODE REVIEW

**Comment by sergiokopplin** [comment]
@SleepWalker i think it does the same as this one: https://github.com/ctrlplusb/react-universally/pull/366

**Comment by SleepWalker** [comment]
@sergiokopplin oh, sorry. I can't understand how does it happend, but this pr is a result of merging feature/redux-opionated into master made today 0o

and when I do something like this:
https://github.com/ctrlplusb/react-universally/compare/master...feature/redux-opinionated
https://github.com/ctrlplusb/react-universally/compare/ctrlplusb:feature/redux-opinionated...SleepWalker:feature/redux-opinionated
https://github.com/ctrlplusb/react-universally/compare/master...SleepWalker:feature/redux-opinionated

I see really strange results.
Current feature/redux-opinionated can not be merged into master without conflicts and the diff looks strange. Probably, I'm doing something wrong and if so, then this PR should be closed. But I can't really understand whats wrong

**Comment by sergiokopplin** [comment]
hey @SleepWalker, it might be because i did an old pr with the next branch, but you're right, it's behind the master now, i think we can go ahead with this one!

**Comment by SleepWalker** [comment]
merged with current master

**Comment by sergiokopplin** [comment]
Hey @SleepWalker, i've done the same work here https://github.com/ctrlplusb/react-universally/pull/489, but it's closed in favor of yours. Duplicated PR!

Can you check if the PR's has the same changes? I've updates some dependencies and routes. Cheers!

**Comment by oyeanuj** [comment]
@SleepWalker Is this ready to merge?

**Comment by SleepWalker** [comment]
@oyeanuj yep.
@sergiokopplin I've applied updates from you PR, but some of them was erased by precommit hook. Regarding Counter route — I leaved it as is, because this route is from master branch. I think it would be better to touch master code as less as possible

**Comment by sergiokopplin** [comment]
@SleepWalker yeah, you're right! Any other specific code was removed?

**Comment by SleepWalker** [comment]
Removed from where? The last commit contains all the meaningful diff from
your's PR except almost all codestyle improvements (some of them I've
reject and the biggest part was erased by precommit hook :( )

So, as you see, our PRs was almost the same...

On Aug 23, 2017 22:42, "Sérgio A. Kopplin" <notifications@github.com> wrote:

@SleepWalker <https://github.com/sleepwalker> yeah, you're right! Any other
specific code was removed?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ctrlplusb/react-universally/pull/471#issuecomment-324441483>,
or mute the thread

**Comment by sergiokopplin** [comment]
Anywhere actually, but it seems ok as you said. 👍

**Comment by oyeanuj** [comment]
@sergiokopplin @birkir Can this be merged then?

**Comment by sergiokopplin** [comment]
I think so! Have you tested it locally @oyeanuj?

**Comment by oyeanuj** [comment]
@sergiokopplin I haven't tested much yet. I was assuming it was tested by others :) I was hoping that once this is merged in, I could then test it together with my existing setup. 

But I understand if you want others to test or bless it first.

**Comment by oyeanuj** [comment]
@sergiokopplin I can confirm that it works well locally, so, I'd say merge if it tests well for you.

**Comment by sergiokopplin** [comment]
Let's merge then! @oyeanuj @SleepWalker @ctrlplusb, let's do that?

**Comment by SleepWalker** [comment]
@sergiokopplin yep, let's do that

**Comment by ctrlplusb** [comment]
Sounds good to me. 😀

**Pull request merged**
