### PR TITLE
[BRANCH][FEATURE] `incubator/stylesheets/styled-components` implementation.

### PR DESCRIPTION
**Pull request by lucianlature**
This is the `incubator/stylesheets/styled-components` branch of the `react-universally` starter kit.

It provides you with the build tooling and configuration you need to kick off your next universal react project with full support for Styled Components.

### CODE REVIEW

**Comment by strues** [comment]
Great work here @lucianlature

**Comment by LorbusChris** [comment]
The export bug in webpack is already fixed on master, let's hope they push out a new beta soon :)

**Comment by LorbusChris** [comment]
related: https://github.com/styled-components/styled-components/issues/301#issuecomment-266235862

Maybe we need to disable babelrc alltogether?

**Comment by lucianlature** [comment]
Could be a solution :)

**Comment by k15a** [comment]
> Maybe we need to disable babelrc alltogether?

You should disable babelrc because otherwise you won't get webpack 2 treeshaking feature which will make the bundle size smaller.

**Comment by ctrlplusb** [comment]
Ah, so the `.babelrc` file in root has been causing issues?

I think we can get around this by adding a `babelrc: false` option the the babel configuration contained within `config/private/project.js`.

**Comment by ctrlplusb** [comment]
We can continue working against the incubator branch directly. :)

**Comment by code-punkt** [comment]
@ctrlplusb I'm not sure what you mean - it's no longer a thing? I added `babelrc: false` to `babelConfig` in `config/private/plugins.js`, which works fine.

**Comment by code-punkt** [comment]
Also, apart from the styling that has been moved to styled-components in this branch, i'd get rid of the globals.css and use global styles of styled-components for that.

If we would do that, i think theres only `normalize.css` still left before we could remove a lot of the happypack-css, css-loader and other shenanigans because all CSS would run through styled-components.

**Comment by ctrlplusb** [comment]
Haha sorry momentary insanity. I was looking at the Babel options not the babel-loader. That's great then thanks. :-)

**Comment by ctrlplusb** [comment]
Agreed on the global cleanup too 👍

**Pull request merged**
