### PR TITLE
Next updates

### PR DESCRIPTION
**Pull request by strues**
- switch ReactDOM.render to ReactDOM.hydrate as per React 16 changes. render deprecates in React 17.

- remove extraneous `babel-polyfill` (doesnt break tests or have any effect).

- Update dependencies, included is HappyPack 4. HappyPack thread pool is set by `os.cpus().length`

- remove react-addons-test-utils as React 16 doesnt use any form of previous addons packages. moved meta charSet above title in html template

- Add requestAnimationFrame (raf) polyfill to `client/polyfill.js`. 

- Upgrade enzyme. Add `enzyme-adapter-react-16` and a setupFile for jest tests. See [enzyme adapter](https://github.com/airbnb/enzyme/tree/master/packages/enzyme-adapter-react-16) docs

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Legendary @strues thanks!

**Review by ctrlplusb — APPROVED** [review]
Great work!

**Comment by sergiokopplin** [comment]
@strues are you using on production? i want to make a deploy to production in the next weeks 🤓

**Comment by diondirza** [comment]
As usual, awesome work @strues

**Comment by oyeanuj** [comment]
@strues When using this in conjunction with the redux branch, I get the following error on the `/posts/2' page:

```sh
Warning: WithJob(Post).componentWillMount(): Assigning directly to this.state is 
deprecated (except inside a component's constructor). Use setState instead.
```

@ctrlplusb Is this a `react-jobs` error instead?

**Pull request merged**
