### PR TITLE
Next => feature/apollo

### PR DESCRIPTION
**Pull request by strues**
Brings feature/apollo up to date with the next branch.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Booyah!  Thanks bro!  I'll review this in the next few days.

**Comment by ctrlplusb** [comment]
Sorry, those next few days have gone by and am swamped still.  Feel confident you have done a great job here though.

Lets wait for `next` to settle before doing a final big merge and release. 😀

**Comment by Aetherall** [comment]
Hey ! How the job going ? :)

When can we expect to see this PR merged?

Cant wait to get the update ! You're doing an awesome job ;)

**Comment by strues** [comment]
This will need some work to merge. I'll pull down the Redux branch and fix it up this afternoon.

**Comment by ddprawira** [comment]
@strues any progress so far?

**Comment by strues** [comment]
Checkout my latest PR. It’s in good shape.

**Comment by strues** [comment]
Closing this in favor of #469 which is essentially finished.

**Pull request closed without merging**
