### PR TITLE
Adding self to contributors list

### PR DESCRIPTION
**Pull request by oyeanuj**
Just adding myself to the contributors list!

### CODE REVIEW

**Comment by sergiokopplin** [comment]
Well deserved!

**Comment by sergiokopplin** [comment]
Hey @oyeanuj, have you added you on the readme file? I guess there's 2 places to add contributors.

**Comment by oyeanuj** [comment]
@sergiokopplin thank you! I wasn't sure about the README file, if that was just pulling from the contributors file or I have to add in both places?

**Comment by sergiokopplin** [comment]
Might be both places man! Not sure, sorry hahaha

**Comment by ctrlplusb** [comment]
I think I got your back on the `next` branch already. Definitely well deserved @oyeanuj! Really appreciate your continuous involvement. ❤️

**Comment by oyeanuj** [comment]
@ctrlplusb thank you, appreciate it!

**Pull request closed without merging**
