### PR TITLE
Removes babel-preset-latest and instead uses babel-preset-env.

### PR DESCRIPTION
**Pull request by strues**
Console has been plague with warnings in various other projects about babel-preset-latest. Preset Env is basically JavaScripts autoprefixer now. Makes things nice :)

[Babel Site](http://babeljs.io/docs/plugins/preset-env/):
> Support all plugins in Babel that are considered latest
> Default behavior without options is the same as babel-preset-latest.
> It won’t include stage-x plugins. env will support all plugins in what we consider the latest version of Javascript (by matching what we do in babel-preset-latest).

### CODE REVIEW

**Comment by birkir** [comment]
Wait so how does this stack up with polyfill.io?

**Comment by ctrlplusb** [comment]
Hey all;

I have taken some time to review this and I think I have settled on something that may be considered controversial at first, but hear me out.

Firstly, to be clear @birkir from what I can tell `babel-preset-env` out the box won't stop our need for polyfill.io, as by default it doesn't use the `babel-polyfill`.  You have to you force it to via the respective [option](https://github.com/babel/babel-preset-env#usebuiltins).  Otherwise it just creates a baseline level of javascript to some degree I am guessing. 

Reading the docs for `babel-preset-env` they recommend you pass in the list of browsers you wish to support, ideally all you need to pass is your lowest common denominator.  I personally feel that we should target IE 10.  We can make this value available via the application centralised configuration.

With this change I think we should then also remove our dependency on polyfill.io and reinclude `babel-polyfill` making sure we activate the associated option on `babel-preset-env`.

Polyfill.io is awesome, but it requires you to know what features you are making use of and then subsequently update the features list to make sure that they get checked for.  In my experience with it I have found that you can all too easily overlook a feature that requires polyfilling for older IE versions etc.  At least with `babel-preset-env` we will automatically get all polyfills for our baseline.  

Yes, the evergreen browsers will still get features they don't need, but then you could push your baseline up if you don't feel that you have any need to support older browser versions.

Thoughts?

**Comment by birkir** [comment]
Hey thanks for the writeup, I did a comparison in file sizes between babel-polyfill and regenerator-runtime, which is my main concerns.

|                | RAW       | Compressed |
|----------------|-----------|------------|
| regenerator-runtime (*current*) | 1,295,660 | 282,426    |
| babel-polyfill | 1,519,476 (+17.3%) | 336,225 (+19.0%)    |
| polyfill.io (IE10) | 75,485 | 18,488 |
| polyfill.io (Chrome 56) | 6,418 | 1,593 |

Polyfill.io with features set to `default,es6` (*Yes*, we forgot to add es6 feature flag 😢 )

What is nice about polyfill.io is that they offer web only things that babel-polyfill doesn't offer, for example IntersectionObserver (which I regularly use).

With babel-polyfill we can safely use almost any feature of babel, ensuring it will be polyfilled for all browsers we care of. But it got me thinking, will default+es6 not cover all babel features?

**Comment by ctrlplusb** [comment]
Hey @strues 

I am closing this as I have done this myself. :)

Thanks for the reference and heads up!

**Pull request closed without merging**
