### PR TITLE
Another bug fixes, tweaks

### PR DESCRIPTION
**Pull request by diondirza**
This PR includes:
- Fix polyfill.io break in some mobile devices
- Fix linter errors
- Remove http protocol for external assets, prevent warning for HTTP mismatch
- Add sample strategy for code splitting using chunk name

### CODE REVIEW

**Comment by diondirza** [comment]
add another commit for today updated deps and some linter fix that prettier revert my changes

**Comment by diondirza** [comment]
@strues that also could work yet I follow to @ctrlplusb `eslint-disable` format in some other places. should I change it?

**Comment by ctrlplusb** [comment]
Great, should we get this merged in? :)

**Comment by ctrlplusb** [comment]
Thank you so much for your efforts here @diondirza 

Super appreciated!  Feels like we are really starting to iron the project out now. 😊

**Pull request merged**
