### PR TITLE
Add chalk and related helpers to replace colors.

### PR DESCRIPTION
**Pull request by strues**
Removes colors dependency for chalk.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Perhaps we should create abstractions for the log statements themselves instead of passing around the chalk palette?

I.e. `logError('foo')`

**Comment by strues** [comment]
I like that idea a lot. I'll put something together in the morning.

**Comment by smirea** [comment]
Hi, sorry, did you get to see this comment? https://github.com/ctrlplusb/react-universally/issues/198#issuecomment-263451639

There seems to be no benefit to replacing `colors` with `chalk` since the functionality you're looking for is supported natively in `colors`. This add a bunch of other unwanted sub-dependencies to the repo

You can get the same functionality by doing `require('colors/safe')`

**Comment by ctrlplusb** [comment]
Thanks @smirea 

@strues - your call, was there any other benefit in using `chalk` over `colors`?

Personally, I am not overly worried about the extra dependencies for something that is used in the development chain only, but perhaps it may be best to stick with `colors` for lowest friction update.

**Comment by strues** [comment]
@ctrlplusb Lets veto the chalk idea and stick with colors.

**Comment by oyeanuj** [comment]
Just wanted to re-touch this issue since I've been running into a Webpack warning with `colors` (with HMR). It seems to be a fairly common issue:  https://github.com/Marak/colors.js/issues/137

Given that and the fact that `colors` hasn't been updated in 2 years, I'd vote for bringing this discussion back up 😄 

Has anyone else run into this issue as well?

**Comment by strues** [comment]
Honestly I'm more used to Chalk **only** because I try and use packages with recent activity. Sort of a rule I stick by to not develop myself into a corner depending on packages that may/may not be supported in the future.

+1 for Chalk

**Comment by oyeanuj** [comment]
@strues I have the same rule, so totally agree. So just created a PR #512 incase there was any interest!

**Pull request closed without merging**
