### PR TITLE
Updated CSP to add backwards compatibility to nonce.

### PR DESCRIPTION
**Pull request by rlindskog**
This seemed to fix everything for me!  Works on Safari.

[#326](https://github.com/ctrlplusb/react-universally/issues/326)
[#341](https://github.com/ctrlplusb/react-universally/issues/341)
[#342](https://github.com/ctrlplusb/react-universally/issues/342)

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Awesome sauce.

**Comment by ctrlplusb** [comment]
Hmmm actually I think this is just opening all the doors. I think this change would just allow unsafe inline scripts for every browser, even for those that support nonces. I think @codepunkt  had some advice here.

**Comment by rlindskog** [comment]
@ctrlplusb I believe browsers that support nonces will see the nonce and ignore the unsafe-inline, according to [this link](https://medium.com/square-corner-blog/content-security-policy-for-single-page-web-apps-78f2b2cf1757#.w9ptzmrxs) (Safari Script Nonces Workaround section).

**Comment by ctrlplusb** [comment]
Awesome thank you for this!

**Comment by codepunkt** [comment]
I hope it does what they say. My first thought was exactly the same as @ctrlplusb - doesn't this just open all the doors?

it's easy to test though - at least manual, for a single browser version :)

**Comment by ctrlplusb** [comment]
# ✨🦄✨

**Comment by rlindskog** [comment]
@codepunkt Just read that as well!

**Pull request merged**
