### PR TITLE
update webpack to 2.2.0-rc.3

### LINKED ISSUE #283: Update webpack

### PR DESCRIPTION
**Pull request by elodszopos**
Closes #283.

### CODE REVIEW

**Comment by strues** [comment]
May want to bump up to rc.3 :)

**Comment by elodszopos** [comment]
Well, I'll be damned :D

image

**Comment by elodszopos** [comment]
Change-log is as follows:

## rc.1 to rc.2:

### Features:
 - Stats output now disables only 15 modules by default (see new option `stats.maxModules`,` --display-max-modules`)
 - Stats for modules now includes a depth for modules which is the distance to the entry point.
add `--display-depth` for CLI to display the module depth in stats

### Bugfixes:
 - Cached modules now correctly reset meta information
 - arrow functions in require.ensure now work correctly

## rc.2 to rc.3:

### Bugfixes:
 - fixes chunk loading in old IEs
 - fixes error which prevented using arrow functions in require.ensure
 - fixes bug when passing function to rules.use
 - fixes bug for --progress output
 - fixes bug with export * and non-harmony modules
 - fixes bug when removing assets from the compilation

**Comment by codepunkt** [comment]
@elodszopos So thats mostly bugfixes as expected from a rc version upgrade. Looks good to me!

**Comment by ctrlplusb** [comment]
Thanks @elodszopos!

Your help is much appreciated. :)

**Comment by elodszopos** [comment]
More to come @ctrlplusb.

**Pull request merged**
