### PR TITLE
Prepare React 15.5

### PR DESCRIPTION
**Pull request by birkir**
- [x] Update dependencies
 - [x] Change import reference for PropTypes.
 - [x] Fix PropTypes warning from third party dependencies.
 - [x] Fix react-dom/test-utils warnings, waiting for https://github.com/airbnb/enzyme/pull/876 to be resolved.

Packages that have new prop-types:
 - [x] react-helmet
 - [x] react-router
 - [x] react-async-component

Everything works like before, just warnings that need to be fixed...

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Sickness!

**Comment by ctrlplusb** [comment]
Wow man, looks like the `prop-types` change is gonna take a while to propagate through all existing packages.

**Comment by strues** [comment]
This move to `prop-types` might be better in the long run, but such a change that requires action from every maintainer is going to be a slow process. Wish there would be a way to disable all the warnings.

**Comment by birkir** [comment]
We could also try to suppress those warnings in the hot client and dev servers, or make them less verbose as they are now.

But the thing is, we're already starting to see packages depend on the external prop-types so we could end up with a two sided problem if we don't move quickly.

I think the most critical thing to solve, is the tests, other stuff can be suppressed.

**Comment by ctrlplusb** [comment]
Hey @birkir and @strues 

Check this out: https://github.com/reactjs/prop-types#compatibility

Looks like a temporary way out until the eco system settles. :)

**Comment by birkir** [comment]
Hey @ctrlplusb 
Im not sure what you mean, we already have react version 15.3 or greater.

But good news, everything except `react-async-component` is done, all tests run good and no warnings - so when you have the time to review my PR and publish we can merge this, if you feel like it.

**Comment by strues** [comment]
@ctrlplusb we could do this, from the link you posted, https://facebook.github.io/react/warnings/dont-call-proptypes.html#fixing-the-false-positive-in-third-party-proptypes

**Comment by ctrlplusb** [comment]
Rad, will try test this all out soon. 🤘

**Comment by ctrlplusb** [comment]
Lets do this. 🚀

**Pull request merged**
