### PR TITLE
CORS security fix

### PR DESCRIPTION
**Pull request by diondirza**
This PR will solve this #431 issue

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Awesome, thanks again @diondirza 

Do you mind rolling back the dependency upgrades?  We can do dependency upgrading seperately.

Also, as we use yarn, when upgrading dependencies please make sure to use yarn, passing in the `--exact` flag.

You can get an interactive upgrade terminal like so:

```
yarn upgrade-interactive --exact
```

👍

**Comment by diondirza** [comment]
No problem, been using that command for every update.

**Comment by diondirza** [comment]
@ctrlplusb done, please review it again

**Comment by ctrlplusb** [comment]
Rad, thanks dude!

**Comment by ctrlplusb** [comment]
You are on a roll!

**Pull request merged**
