### PR TITLE
Use .bablrc to configure babel.

### PR DESCRIPTION
**Pull request by trbngr**
First off, fantastic starter kit! Thank you for putting it together.

I wasn't able to figure out why Relay wasn't working for me. After a day of tearing my hair out, I realized that the js loader config in weback was cloberring my .babelrc settings.

I put the loader settings in the .babelrc file and everything came to life.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Hi @trbngr!

Thank you for your compliment and for your interest in expanding this boilerplate / starter kit.

I've had a look at your PR.  I have a couple of questions and a note...

_Questions_

- What functionality was Relay specifically relying upon from babel?
- I have no experience with GraphQL and Relay as of yet.  I assume your Relay implementation is bundled with the client?
- What is your reasoning behind using the `loose` mode webpack preset? Is it purely a bundle size optimisation?
- I am not familiar with the `passPerPreset` flag in the .babelrc file.  What is its intention?

_Note_

I am open to using a .babelrc file if we get the right configuration.  However, there are a few things that you need to be aware of about the current babel configuration that exists within the webpack loaders.  

If you not if the `if` helpers you will see that I specifically do not transpile the code when we are targeting the `node` environment.  This is because v6 of node supports most of the es2015 syntax out of the box.  I would like us to take advantage of that fact as we may get a more performant experience as the node server may be more optimised for the natural ES6 syntax.  The syntax that it doesn't support is ES6 modules, which is fine because webpack 2 handles them natively for us and will do the necessary transpilation on our behalf.  

The client bundle needs to be transpiled to ES5 as you know, but again, webpack 2 has the native ES6 modules support and it requires a handle on them in order to do its treeshaking effectively.  Hence my usage of `babel-preset-es2015-webpack` when we are targetting the browser/client - this preset does all ES6 transpilation except for ES6 modules.

I am happy for us to move to .babelrc for the babel configuration.  It's probably where most people would look first for their babel config, however, I want us to keep the semantics described above.

**Comment by trbngr** [comment]
> What functionality was Relay specifically relying upon from babel?
Relay requires a Babel plugin to transform some string templates into literals based on a well-define schema. I suppose I could have added my plugin definition into the webpack config, but, IMO, that goes against convention.

I totally understand the server scenario. But I don't have a solution ATM. 

Relay is more than likely not taking part in SSR, so maybe it's fine. IDK.

> I have no experience with GraphQL and Relay as of yet. I assume your Relay implementation is bundled with the client?

Relay is a client-side library. So yes.

> What is your reasoning behind using the loose mode webpack preset? Is it purely a bundle size optimisation?

No reason at all. Just what I had from a previous package.json. Come to think of it, I don't want it at all. Thanks for questioning that. ;)

> I am not familiar with the passPerPreset flag in the .babelrc file. What is its intention?

This required to support Relay in React Native apps. You can read about it [here].(https://facebook.github.io/relay/docs/guides-babel-plugin.html#react-native-configuration) 

I agree with all your notes. And I applaud you for taking the time to think about this PR before merging. However, I believe there is a flaw in this particular example WRT tree-shaking. I'm pretty sure that feature is out the window when combining a vendor bundle with code-splitting. I do see that you didn't add React Router to the vendor bundle though. That's good ;)

**Comment by ctrlplusb** [comment]
Awesome to hear some confirmation about tree shaking and the vendor bundle approach.  I actually suspected this myself and had opened an issue (#2) to investigate this.  Do you have any blogs/issues/posts that discuss/verify this as being a known issue.  I am happy to remove the vendor bundle approach. I definitely want to keep the tree shaking feature active.

In regards to Relay's requirements - I will have a read of that link you have provided and see if I can come up with any solutions.

**Comment by trbngr** [comment]
Well. That's the good thing about .babelrc. You don't need a solution to that ;)

I can't recall the blog I read about it, but when I read the comment, I promptly tested the theory. It's an issue.

**Comment by ctrlplusb** [comment]
I've removed the vendor bundle and closed that issue, thank you for verifying that was an issue.

In regards to the babel loader updates for Relay - can you try add the necessary config to the webpack loaders in the interim?  I don't want to add "feature-specific" configuration to this boilerplate, but we can definitely still try to move the existing structure to .babelrc files if the solution is clean.

For now I may create an empty .babelrc file with a comment stating that all babel config is created and loaded via the webpack loader.

**Comment by trbngr** [comment]
I've solved my issues on my side. The whole reason for this PR was to bring attention to the issues I ran into. 

I think adding an empty .babelrc with an explanation is perfectly acceptable.

**Comment by trbngr** [comment]
I'm not sure removing vendor bundle all together is the right thing to do. The issues I saw were the duplication of code in split chunks.

I'll do more testing tomorrow. I have to get off this computer thingy for a bit. ha

**Comment by ctrlplusb** [comment]
Great!  I appreciate you looking into this.

**Comment by chaffeqa** [comment]
Just as a dis-interested party, I have made projects before that have multiple babel configurations.  An example would be a `.babelrc` file to define how babel transpiles gulp files and runs them, and then a `babel config` (in webpack) to define how to transpile the browser javascript.

Due to that, if possible I try to keep babel config options inside the tool that is able to define them for that tool *when possible*... otherwise fallback to `.babelrc`

For that reason I would say: leave the webpack babel config in the webpack config definition

**Comment by ctrlplusb** [comment]
I've added a .babelrc placeholder file with a comment informing users of our reasoning in having the babel config contained within the loaders.

Closing this PR.

**Pull request closed without merging**
