### PR TITLE
Update react router alpha to beta

### PR DESCRIPTION
**Pull request by diondirza**
React router has released beta version of it, I think we should update our deps too.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Thanks for this @diondirza!  It is a helpful reference. :)

I have been trying an upgrade myself, however, there are still some issues to be resolved in regards to SSR.

**Comment by diondirza** [comment]
What kind of issue is it? I also had some issue with latest react router version, and have posted the [issue](https://github.com/ReactTraining/react-router/issues/4480) on their github, do you face this kind of issue?

**Comment by carsonperrotti** [comment]
@diondirza That's the one he is referring to. Waiting for it to make it into a release.

**Comment by diondirza** [comment]
@carsonperrotti ah i see, i also looking forward to it.

**Comment by birkir** [comment]
I get annoying `forceUpdate`on a unmounted component error every time I try to navigate back/forward (everything else than history.push i think).

**Comment by ctrlplusb** [comment]
Big big big update to this branch coming soon. With tons of fixes.

**Comment by diondirza** [comment]
@birkir I don't see any error you've mentioned either in browser or console on my branch. Is this related to some lib?

**Comment by birkir** [comment]
@diondirza False alarm. I traced the source of the problem to `react-async-component` (or react-tree-walker to be exact), it is badly broken.

**Comment by diondirza** [comment]
I think this PR not relevant anymore, will make another PR for solving 404 status code

**Pull request closed without merging**
