### PR TITLE
Adds Dockerfile and docker-compose.yml

### LINKED ISSUE #46: Add a basic Dockerfile
Also include #12 in readme or dockerfile comments.

### PR DESCRIPTION
**Pull request by strues**
Resolves #46 

Contains Node v7 with Yarn installed on Alpine Linux 3.4

### CODE REVIEW

**Comment by ctrlplusb** [comment]
This is great @strues 

Thanks!

I am a bit of a docker noob, so I am gonna let this PR sit for a while until I wrap my head around it.  I definitely would like us to explore the production use case a bit further too.

What do you see as the major advantages of using the docker container during development vs the "standard" method?

**Comment by strues** [comment]
@ctrlplusb I feel like Docker in this case is slightly unnecessary, but thats just my opinion. I know a lot of people use Docker for everything in development. I usually only run my databases in containers until production.

**Comment by ctrlplusb** [comment]
@strues I would have to agree.  I can't see the obvious value in running docker in development.

Lets keep this running though.  I am definitely interested in a "production" container configuration.

**Comment by oyeanuj** [comment]
@strues Wondering if you are maintaining a docker version in your own work for `react-universally`? If yes, could you share your docker config?

**Comment by mschipperheyn** [comment]
I use Dokku myself with React Universally. Curious to understand the difference in use cases, advantage, disadvantage?

**Pull request closed without merging**
