### PR TITLE
Add support for Internet Explorer

### PR DESCRIPTION
**Pull request by datoml**
We all love internet explorer, right? :)

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Hey @datoml!

Thanks for this. 

Hmmm, I actually intentionally left out babel-polyfill as it is quite heavy in payload and instead dropped in the polyfill.io service which is supposed to polyfill the features that your browser (IE or whatever) is missing.  Are you experiencing issues with IE currently?

**Comment by datoml** [comment]
I was just curious if it is working on IE.
Adding the babel-polyfill was the fastest solution for me because I don't know what polyfill for IE would fit the best :).

**Comment by birkir** [comment]
Polyfill.io has support for `Object.assign`, if you want to enforce it, take a look at the documentation at https://polyfill.io/v2/docs/api

Here is a result for IE7 user-agent:
```bash
https://cdn.polyfill.io/v2/polyfill.js?ua=Mozilla%2F5.0%20(Windows%3B%20U%3B%20MSIE%207.0%3B%20Windows%20NT%206.0%3B%20en-US)
```

**Comment by ctrlplusb** [comment]
Hey @datoml please see #374 💖

**Comment by datoml** [comment]
Fixed #374

**Pull request closed without merging**
