### PR TITLE
0.0.0.0 doesn't work on windows

### PR DESCRIPTION
**Pull request by datoml**
Yeah, I'm the windows guy :D

### CODE REVIEW

**Comment by elektronik2k5** [comment]
I'm against merging this because I'd like my dev environment to be reachable also outside of the development machine, over the network. It allows me to test on different devices on my network.

I'm not an expert on windows, but I don't see any reason why it wouldn't work as is and I think _that's_ worth investigating @datoml .

**Comment by datoml** [comment]
I searched a bit around for this problem and it seems like its a windows problem.
No idea how we can fix this then ¯\_(ツ)_/¯.

**Comment by birkir** [comment]
0.0.0.0 is working on my windows machine fine.

We may have to incorporate something like they are discussing here https://github.com/senecajs/seneca-transport/issues/37

But untill then just add HOST=127.0.0.1 to your dotenv.

Binding to 0.0.0.0 is absolutely critical for docker, saas and allowing outbound connections to work.

**Comment by datoml** [comment]
@birkir Thanks.
I wasn't aware of this with docker. Never used it.
I am using now the .env file and it works. So I think I can delete this PR :).

**Comment by birkir** [comment]
Good stuff

**Pull request closed without merging**
