### PR TITLE
Run React-Universally on HTTP/2

### PR DESCRIPTION
**Pull request by lucianlature**
Improve the page speeds and create better user experience by [changing the server protocol to HTTP/2.](http://ivanjov.com/running-express-koa-and-hapi-on-http-2/)

This PR is only for express, but if approved I can also make it work for `Koa2` and `hapi` (probably I will have to create a feature branch just for `hapi`).

Just run:
- `yarn install`
- `yarn run development`
- then go to `https://localhost:1337`.

Enjoy the new supported protocol:

screen shot 2017-01-22 at 21 02 47

### CODE REVIEW

**Comment by codepunkt** [comment]
Getting http/2 support is good. You would not want to deploy those development certificates to a production system and might want to restrict this to `development`.

I had problems doing this and deploying to `now`. Did you try if that still works?

**Comment by lucianlature** [comment]
@codepunkt Code restricted to `development` only. Tried to deploy it to `now` using command `now -e SSL_CERTIFICATE=false`, but no success so far, some issues on their part.

Here's attached another pic with self-signed certificate for `localhost`, in `production` mode:

screen shot 2017-01-23 at 14 51 34 2

**Comment by ctrlplusb** [comment]
Nice on http2 @lucianlature!!!! 🎉

Also finding the development based https quite interesting - so you are attempting to allow us to run https on dev server to promote better testing of this if we plan to deploy to an https target?

**Comment by lucianlature** [comment]
@ctrlplusb That's exactly what I wanted and it is working just great ;)

**Comment by lucianlature** [comment]
@ctrlplusb Don't know exactly the cause, but after merging the latest from `next` branch, the loading time of the home page decreased from an average `950ms` to less than `700ms` in `production` mode. Impressive!

**Comment by ctrlplusb** [comment]
Yep, we are hitting 100/100 on the Lighthouse PWA score now too. 🚀

**Comment by ctrlplusb** [comment]
Granted, it's a nothing app at the moment, so 700ms is probs still on the crazy scale. 😂

**Comment by codepunkt** [comment]
I think there is still a lot to be discussed here.

I can see `spdy` being applied in development environment only in the hot reloader code. The server code simply checks `config.SSLCertificate`. If it is true, `spdy` is used - even in production. Is there a mechanism that prevents using the development certificates bundled in the repository in production? How would you deploy this to a host with real certificates?

Speaking of `now`, there is an easy solution for that - don't wrap `express` in `spdy` when `process.env.NOW` is set.

**Comment by bradennapier** [comment]
FYI: C9 environments by default provide 3 SSL domains to use so all my dev is on SSL Certified while being able to share with others and with hot reloading - having 2-3 people working at once means the app updates live - can be fun to watch an app get built out of nothing :)

**Comment by LorbusChris** [comment]
www.letsencrypt.org is also great for SSL certificates!

**Comment by lucianlature** [comment]
@codepunkt In this PR, we have `const cmd = 'now -e SSL_CERTIFICATE=false';` in `tools/scripts/deploy.js`, so if you need to deploy to `now`, SSL certification is not active. This should also be the case when deploying to a different host.

For a host with real certificates, you will already have your own, I presume, so you just have to point to their location in configuration.

**Comment by codepunkt** [comment]
I suggest not wrapping the express server into `spdy` when deployed to now instead of disabling the ssl option. This breaks production deployments to `now`.

**Comment by birkir** [comment]
Hey, cool PR - just wanted to add few notes.

1) Maybe add `config('spdy.enabled')` for toggling it on/off.
2) Don't ship self-signed certificates, ever. Provide a guide how to create them and add them to a keychain to suppress the warnings.
3) Add a push of the bundled assets for quicker render (the real gain of having HTTP/2).

```js
// ./server/middleware/reactApplication/index.js
Object.entries(clientEntryAssets)
.forEach((type, path) => {
  response.push(path, {
    request: {
      accept: '*/*',
      // TODO: Add other headers, like cache, e-tags, etc.
    },
    response: {
      // Only two mime types are used, using the mime package is a bloat for now.
      'content-type': (type === 'css') ? 'text/stylesheet' : 'application/javascript',
    },
  })
  .end(fs.readFileSync(resolve(appRootDir.get(), `./build/${path}`)));
});
```

**Comment by ctrlplusb** [comment]
Hey all, I listened to the node podcast on the state of HTTP2 within node.  Given the comments from the core team I would prefer we hold off of any HTTP2 integration for now.  I am going to close this so as not to have stale PRs.  Hopefully we can revisit this in the future.

**Pull request closed without merging**
