### PR TITLE
upgrade dependencies.

### PR DESCRIPTION
**Pull request by l-7-l**
This PR mainly upgrades **webpack** and some dependencies

@ctrlplusb @hguillermo  Please give me some advice.

### CODE REVIEW

**Comment by l-7-l** [comment]
wait: [Replace webpack.optimize.UglifyJsPlugin to UglifyJsPlugin](https://github.com/NekR/offline-plugin/pull/353)

**Comment by hguillermo** [comment]
@chenyang-biu close to finish your PR? I would like to try this boilerplate with react 16. If I can help let me know.

**Comment by l-7-l** [comment]
@hguillermo I'm sorry, I've been looking for work these days....

**Comment by l-7-l** [comment]
please enlighten.

**Comment by birkir** [comment]
Thanks for the PR but now the `next` branch has everything (and more).

**Comment by sergiokopplin** [comment]
👏

**Comment by hguillermo** [comment]
Thanks @birkir. Are you planning to merged `next` to `master` soonish?

**Comment by birkir** [comment]
We are waiting on one dependency to be released, react-tree-walker 👍

**Comment by hguillermo** [comment]
Perfect. I guess I will start from `next` and update it later.

**Comment by unleashit** [comment]
Just wondering... are the new updates to react-tree-walker going to support renderToNodeStream, or will the app still have to use renderToString first? Seems like one of the primary benefits to R16 is the ability to stream server rendering, which appreas to not be happening right now with this repo except at the end as a string.

**Comment by hguillermo** [comment]
@birkir Do you know when are you merging next to master? What are the pending things if I use next as a base for my next project? Thanks

**Comment by birkir** [comment]
I do not.
My buddy, the project owner, @ctrlplusb is the man to ask! 👍

**Comment by hguillermo** [comment]
Thanks @birkir. 

@ctrlplusb: when do you think you will merge next to master? is it something pending?

**Pull request closed without merging**
