### PR TITLE
Webpack DLLs and HappyPack

### PR DESCRIPTION
**Pull request by strues**
This is for issue 105. It adds Webpack DLL plugin and HappyPack (for JavaScript files).

I've updated the README, example .env file, and left comments within the configuration.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
@strues - sorry this is still on my radar, thanks so much for the PR.

There is more than I expected to consider here, so I am going to give myself a few days in order to minimize oversights. I'll keep you posted.

Thanks!

**Comment by strues** [comment]
Sure thing. Let me know if you have any questions.

**Comment by EugeneHlushko** [comment]
Very nice @strues, good job!

**Comment by strues** [comment]
I've improved the implementation of HappyPack so that you are able to use an instance of HP per file type. I'll implement it into my branch and add to this PR. Expect it to come tomorrow morning. I've gotta get a bit of sleep before work.

**Comment by ctrlplusb** [comment]
Awesome @strues thanks for your work on this!  

Do you mind adding me as a collaborator to this PR? Then we can work together to finalise the functionality.

Thanks again for your work on this!  So great to have some help. :)

**Comment by strues** [comment]
@ctrlplusb No problem. I went ahead and added you as a contributor to my fork. Also completed adding in a secondary HP instace.

**Comment by ctrlplusb** [comment]
@strues FYI I am working on this now. :)

**Comment by ctrlplusb** [comment]
@strues - I've refactored quite a bit...

The big change is that the vendor dll is only implemented for development, and is completely automated by the development server.  You don't need to run the npm command anymore - so I have removed it.

Have a play and let me know your thoughts.

**Comment by ctrlplusb** [comment]
@EugeneHlushko if you have experience with these features we would appreciate your feedback too. :)

**Comment by strues** [comment]
@ctrlplusb Just got into the office and pulling it down now to check it out.

**Comment by ctrlplusb** [comment]
@strues Great! Thanks!

Scheduling in for a merge. :)

**Pull request merged**
