### PR TITLE
Webpack and HMR 4

### PR DESCRIPTION
**Pull request by birkir**
This pull-request upgrades webpack and hot-module-reload respectively to the major version 4.

 - Webpack 4.1.0
 - Hot Module Reload 4.0.0
 - Happypack 5.0.1-beta (Beta... well it just changes how the internal plugin api is called, so really nothing has changed)
 - Remove webpack-md5-hash (Irrelevant now)
 - Add json extension to modernizerrc (Json loader ships by default and it must have the ext).

When this has been validated and merged, we can continue to add and benefit from new features in Webpack 4 that we currently don't have enabled.

### CODE REVIEW

**Comment by oyeanuj** [comment]
@birkir This is awesome, thank you for getting this started. Just a question -  With the new production mode, can't we also take out a lot of the `isProduction` code in the `configFactory`, like the minimizing and uglifying the code?

And once we upgrade to Babel 7, we would be all caught up and with simplified config!

**Comment by newsiberian** [comment]
@birkir, hi. Are you succeed to run this?
I'm gettting stuck after this:
```bash
WEBPACK: Creating a development bundle configuration for the "client"
(node:8645) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

**Comment by birkir** [comment]
@oyeanuj That was the plan!
@newsiberian This is just a warning. Inevitable we still have to use HappyPack for multi-threaded bundling. Everything works fine.

**Comment by ctrlplusb** [comment]
Awesome! Thanks so much for this!

**Review by ctrlplusb — APPROVED** [review]
🎉

**Comment by newsiberian** [comment]
Hi, @birkir, @ctrlplusb, once again I want to return to this. Are you don't using `react-async-component`? Because I still have many errors related with it. One of them described [here](https://github.com/ctrlplusb/react-tree-walker/issues/19) and [here](https://github.com/gaearon/react-hot-loader/issues/832)

**Comment by newsiberian** [comment]
Also getting this many times:
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit`
Catched [here](https://github.com/ctrlplusb/react-universally/blob/master/internal/development/hotNodeServer.js#L41)

**Comment by birkir** [comment]
I think all of your reported errors are not related to this PR.
We could definitely do some work on async things, like use `import()` for native webpack code splitting etc. But step 1 is getting webpack 4 in, then get feedback so we can incrementally get closer.

Thanks

**Comment by sergiokopplin** [comment]
👏

**Comment by oyeanuj** [comment]
@birkir @sergiokopplin Is code splitting still working for you after this PR? If yes, could you share the config that you have for chunking?

**Comment by sergiokopplin** [comment]
hey @oyeanuj, i need testing first, i`m not using that yet

**Pull request merged**
