### PR TITLE
Feature/apollo

### PR DESCRIPTION
**Pull request by strues**
@This is a rewrite of #367.

I saw there was interest in this again still so spent a few hours tonight. Everything works, but I've got a few things left to do. 

**New:**
- Post listing page w/ 100 posts
- Single post page for each
- Minor dependency updates

- [x] Write comments
- [x] Clean up dead code
- [x] Re-enable helmet's CSP (wasnt playing nice with graphiql)

### CODE REVIEW

**Comment by ddprawira** [comment]
really love to see this get merged, gonna use Apollo and GraphQL in next project.

**Comment by diondirza** [comment]
really looking forward to have this feature branch get merged

**Comment by strues** [comment]
Cleaned up and updated dependencies. I experienced an error early this morning which looked like:

```
TypeError: Cannot read property 'ReactCurrentOwner' of undefined
 at Object.<anonymous> (~/node_modules/react-apollo/node_modules/react-dom/cjs/react-dom-server.development.js:3534:36)
```

If for whatever reason you get this error, checkout https://github.com/apollographql/react-apollo/issues/826 the solution `cd node_modules/react-apollo && npm remove react-dom` works. I've not run across this issue in any of my other Apollo projects. It's isolated, but not isolated enough. Yet.

I removed react-jobs because, it's not necessary with GraphQL/Apollo data fetching. We're basically close to a merge at this point. Let me know any feedback

**Comment by ctrlplusb** [comment]
Frikken awesome @strues!

Totally agreed on removing react-jobs - definitely not needed in this context.

I won't have time to give it a proper review so would defer this responsibility to any of the others who may have a spare moment.

**Comment by diondirza** [comment]
@strues that error happened on my local, thanks for pointing out the solution and now runs perfectly. Except will find error with `yarn check` command, I think that need to be solved. Anyway would be glad if there are some documentation about apollo implementation in the sources.

**Comment by strues** [comment]
Additional documentation added. Shall I resolve the merge conflicts and merge this baby?

**Comment by diondirza** [comment]
Please merge this baby @strues. Also maybe you could include `graphql-tag/loader` to preprocess import from `.graphql` files, that would be nice.

**Comment by strues** [comment]
Merged.

**Pull request merged**
