### PR TITLE
put meta[charset] before title

### PR DESCRIPTION
**Pull request by ambar**

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Thanks for this @ambar - is this considered best practice? Do you have any reference material for interests sake?

**Comment by ambar** [comment]
@ctrlplusb https://github.com/sonarwhal/sonar/blob/master/docs/user-guide/rules/meta-charset-utf-8.md

> Must be inside the <head> element and within the first 1024 bytes of the HTML, as some browsers only look at those bytes before choosing an encoding.

> Moreover, it is recommended that the meta tag be the first thing in the <head>. This ensures it is before any content that could be controlled by an attacker, such as a <title> element, thus, avoiding potential encoding-related security issues (such as the one in old IE).

**Comment by ctrlplusb** [comment]
TIL 😄

**Review by ctrlplusb — APPROVED** [review]

**Comment by ctrlplusb** [comment]
Thanks again @ambar! Really appreciate the contribution ❤️

**Pull request merged**
