### PR TITLE
[Incubator/state/apollo] Branch up-to-date.

### PR DESCRIPTION
**Pull request by lucianlature**
Merged the latest `incubator/master` into `incubator/state/apollo`.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Ouch, sorry, it looks like we both picked up this one!

**Comment by ctrlplusb** [comment]
screenshot 2016-12-12 21 34 10

**Comment by lucianlature** [comment]
It's the same for incubator/state/redux?...Perhaps I can start working on `preact` branch feature :)

**Comment by ctrlplusb** [comment]
I decided to simply the branch a lot removing all the redux complexity.  Trying to keep it focused on bare bones graphql implementation.  Still doing work on it.

**Comment by ctrlplusb** [comment]
Hmmm, in regards to `preact`, let me have a think on this for a bit.  I am a bit concerned about our branch numbers and want to see if we can evolve a decent workflow in which they are all well maintained etc.  We have tons already so let's keep to these for now until we nail down our process. :)

Thanks for your enthusiasm and help though! You have been amazingly awesome.

**Comment by lucianlature** [comment]
@ctrlplusb You're welcome! I will take good care of the branches I've started. Looking forward for more features to be added, great job! 👍

**Pull request closed without merging**
